// Code generated by go generate; DO NOT EDIT.
package test_package

var EnumValues = map[Enum]string{

	EnumValue1: "EnumValue1",

	EnumValue2: "EnumValue2",

	EnumValue3: "EnumValue3",

	EnumValue4: "EnumValue4",
}
